big update build-openwrt-package_only.yml build-openwrt-package_only_with_ccache-redis-docker.yml build-openwrt.yml

diff --git a/.github/workflows/build-openwrt-package_only.yml b/.github/workflows/build-openwrt-package_only.yml
--- a/.github/workflows/build-openwrt-package_only.yml
+++ b/.github/workflows/build-openwrt-package_only.yml
@@ -8,7 +8,7 @@
 env:
   # DO NOT CHANGE the following here, set them only in forked repo's Settings->Secrets page
   # You don't need to set docker_registry if you are using the default Docker Hub Settings->Secrets
-  DK_REGISTRY: ${{secrets.docker_registry}}
+  DK_REGISTRY: ${{vars.docker_registry}}
   DK_USERNAME: ${{vars.docker_username}}
   DK_PASSWORD: ${{secrets.docker_password}}
   SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
@@ -16,6 +16,8 @@ env:
   ACTIONS_ALLOW_UNSECURE_COMMANDS: true
   OPT_UPDATE_FEEDS: "1"
   # OPT_REBUILD: "1"
+#  OPT_PACKAGE_ONLY: "1"
+#  OPT_PUSH_WHEN_FAIL: "1"
   OPT_PACKAGE_ONLY: "1"
   OPT_PUSH_WHEN_FAIL: "1"
   REPOSITORY_GH_PAGES_RELEASES: ${{vars.VARG_REPOSITORY_GH_PAGES}} # eg berlin4apk/openwrt-releases or openlumi/releases 
@@ -59,17 +61,23 @@ on:
         #required: true
         #default: 22.03.3-rsync-mini
         type: boolean
-        default: true
+        #default: true
+        default: false
       OPT_REBUILD:
         type: boolean
+        default: false
       OPT_PACKAGE_ONLY:
         type: boolean
         default: true
       OPT_PUSH_WHEN_FAIL:
         type: boolean
-        default: 1
+        default: false
+      OPT_IGNORE_ERRORS:
+        type: boolean
+        default: false
       OPT_DEBUG:
         type: boolean
+        default: false
 ##      continue-on-error:
 ##        type: boolean
 #    env:
@@ -150,6 +158,8 @@ jobs:
       run: echo "OPT_PACKAGE_ONLY=1" >> $GITHUB_OUTPUT
     - if: ${{ github.event.inputs.OPT_PUSH_WHEN_FAIL && github.event.inputs.OPT_PUSH_WHEN_FAIL != 'false' }}
       run: echo "OPT_PUSH_WHEN_FAIL=1" >> $GITHUB_OUTPUT
+    - if: ${{ github.event.inputs.OPT_IGNORE_ERRORS && github.event.inputs.OPT_IGNORE_ERRORS != 'false' }}
+      run: echo "OPT_IGNORE_ERRORS=1" >> $GITHUB_OUTPUT
     - if: ${{ github.event.inputs.OPT_DEBUG && github.event.inputs.OPT_DEBUG != 'false' }}
       run: echo "OPT_DEBUG=1" >> $GITHUB_OUTPUT
 #    - if: ${{ github.event.inputs.continue-on-error }}
@@ -227,6 +237,10 @@ jobs:
     - name: Configure docker
       if: env.SKIP_TARGET == '0'
       run: scripts/cisteps/build-openwrt/04-configure_docker.sh
+
+    - name: Configure host modification (04-mod-host.sh)
+      if: env.SKIP_TARGET == '0'
+      run: scripts/cisteps/build-openwrt/04-mod-host.sh
 
     - name: Check status of builders
       if: env.SKIP_TARGET == '0'
@@ -309,17 +323,17 @@ jobs:
           builderDL-
 
 
-#    - name: link dl to /dev/shm/1001/DLccache/
-    - name: ls /dev/shm/1001/DLccache/
-      #if: env.SKIP_TARGET == '0' && env.TEST != '1'
-      run: |
-       ls -latR ${{ env.HOST_WORK_DIR }} ||:
-       ls -la /dev/shm/1001/DLccache /home/builder/openwrt/dl DL_DIR $DL_DIR ||:
-       mkdir -p /home/builder/dl ||:
-       ln -s /home/builder/openwrt/dl /home/builder/dl ||:
-       export -p | grep DIR
-       #ln -s /dev/shm/1001/DLccache/ /home/builder/openwrt/dl ||:
-       #ls -la /dev/shm/1001/DLccache /home/builder/openwrt/dl ||:
+##    - name: link dl to /dev/shm/1001/DLccache/
+#    - name: ls /dev/shm/1001/DLccache/
+#      #if: env.SKIP_TARGET == '0' && env.TEST != '1'
+#      run: |
+#       ls -latR ${{ env.HOST_WORK_DIR }} ||:
+#       ls -la /dev/shm/1001/DLccache /home/builder/openwrt/dl DL_DIR $DL_DIR ||:
+#       mkdir -p /home/builder/dl ||:
+#       ln -s /home/builder/openwrt/dl /home/builder/dl ||:
+#       export -p | grep DIR
+#       #ln -s /dev/shm/1001/DLccache/ /home/builder/openwrt/dl ||:
+#       #ls -la /dev/shm/1001/DLccache /home/builder/openwrt/dl ||:
 
 
     - name: Clone/update OpenWrt
@@ -381,14 +395,22 @@ jobs:
         #verbose: 2
         verbose: 1
         install-from-github: true
-        dont-do-config: true
+        dont-do-config: false
+        #dont-do-config: true
 
     - name: set cache_dir 
       #if: env.SKIP_TARGET == '0' && env.TEST != '1'
       run: |
+       ccache -V
+        echo "#################"
+       ccache -p
+        echo "#################"
        ccache --set-config=cache_dir=${{ env.HOST_CCACHE_DIR }} ||:
+        echo "#################"
        ccache --set-config=max_size=1500M
+        echo "#################"
        ccache --set-config=compression=true
+        echo "#################"
        ccache -p
 
 
