Update build-openwrt-package_only_with_ccache-redis-docker.yml

diff --git a/.github/workflows/build-openwrt-package_only_with_ccache-redis-docker.yml b/.github/workflows/build-openwrt-package_only_with_ccache-redis-docker.yml
--- a/.github/workflows/build-openwrt-package_only_with_ccache-redis-docker.yml
+++ b/.github/workflows/build-openwrt-package_only_with_ccache-redis-docker.yml
@@ -91,8 +91,8 @@ jobs:
   container-job:
     # Containers must run in Linux based operating systems
     runs-on: ubuntu-latest
-    needs: build
-    if: ${{ !cancelled() && (success() || failure() || needs.previous-job.result == 'skipped') }}
+#    needs: build
+#    if: ${{ !cancelled() && (success() || failure() || needs.previous-job.result == 'skipped') }}
     continue-on-error: true
     strategy:
       fail-fast: false
@@ -156,7 +156,11 @@ jobs:
           docker exec ${{ job.services.redis-y9g98g58d.id }} /bin/sh -x -c 'echo "loglevel verbose" >> /etc/redis/redis.conf'
           docker exec ${{ job.services.redis-y9g98g58d.id }} /bin/sh -x -c 'echo "# see https://github.community/t/how-do-i-properly-override-a-service-entrypoint/17435/8" >> /etc/redis/redis.conf'
           docker exec ${{ job.services.redis-y9g98g58d.id }} /bin/sh -x -c 'echo "# https://hub.docker.com/_/redis" >> /etc/redis/redis.conf'
-          # docker kill --signal=SIGHUP ${{ job.services.redis-y9g98g58d.id }} ||:
+          docker kill --signal=SIGHUP ${{ job.services.redis-y9g98g58d.id }} ||:
+      - name: Sleep for 30 seconds
+        run: sleep 300s
+        shell: bash
+
 
       - name: "wait for job finish"
         run: |
